
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ABOURA
 */
public class Enseignant extends javax.swing.JFrame {

    /**
     * Creates new form Enseignant
     */
    public Enseignant() {
        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        prenomField = new javax.swing.JTextField();
        matiereField = new javax.swing.JTextField();
        ajouterBtn = new javax.swing.JButton();
        supprimerBtn = new javax.swing.JButton();
        modifierBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        homeBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id Matiére :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prénom :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nom :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        getContentPane().add(nomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 90, -1));
        getContentPane().add(prenomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 90, -1));
        getContentPane().add(matiereField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 90, -1));

        ajouterBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        ajouterBtn.setForeground(new java.awt.Color(0, 153, 204));
        ajouterBtn.setText("Ajouter");
        ajouterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ajouterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 40));

        supprimerBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        supprimerBtn.setForeground(new java.awt.Color(0, 153, 204));
        supprimerBtn.setText("Supprimer");
        supprimerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(supprimerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 140, 40));

        modifierBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        modifierBtn.setForeground(new java.awt.Color(0, 153, 204));
        modifierBtn.setText("Modifier");
        modifierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierBtnActionPerformed(evt);
            }
        });
        getContentPane().add(modifierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 140, 40));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "nom", "prenom", "matiére"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 10, 290, 260));

        homeBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(0, 153, 204));
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 283, 110, 40));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection con2;
    PreparedStatement insert;
    private void table(){
        int c;
        try{
            Connect c1 = new Connect();
            con2 = c1.getConnection();
            insert = con2.prepareStatement("select * from enseignant");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            c = rss.getColumnCount();
            DefaultTableModel Df= (DefaultTableModel)Table.getModel();
            Df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int a=1;a<=c;a++){
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("nom"));
                    v2.add(rs.getString("prenom"));
                    v2.add(rs.getString("idMat"));


                }
                Df.addRow(v2);
            }
           
            
        }catch(Exception e) {
            System.err.println(e);
        }
    }
    private void ajouterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBtnActionPerformed
        // TODO add your handling code here:
         String name = nomField.getText();
         String prenom = prenomField.getText();
         String matiere = matiereField.getText();

        try{
        Connect c = new Connect();
        con2 = c.getConnection();
        insert = con2.prepareStatement("insert into enseignant(nom,prenom,idMat)values(?,?,?)");
        insert.setString(1, name);
        insert.setString(2, prenom);
        insert.setString(3, matiere);
        insert.executeUpdate();
        JOptionPane.showMessageDialog(this, "Enseignant ajoutée");
        nomField.setText("");
         prenomField.setText("");
         matiereField.setText("");
        nomField.requestFocus();
        table();
        
    }catch(Exception e){
        System.err.println(e);
    }
        
    }//GEN-LAST:event_ajouterBtnActionPerformed

    private void supprimerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df= (DefaultTableModel)Table.getModel();
        int selectedIndex = Table.getSelectedRow();
        
        try{
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            int dialogResult = JOptionPane.showConfirmDialog(null,"voulez vous supprimer cet enseignant","warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                Connect c = new Connect();
                con2 = c.getConnection();
                insert = con2.prepareStatement("delete from enseignant where id =?");
                insert.setInt(1, id);
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this, "Enseignant suprimée");
                nomField.setText("");
                prenomField.setText("");
                matiereField.setText("");

                nomField.requestFocus();
                table();
            }
            
            
            
        
    }catch(Exception e){
        System.err.println(e);
    }
        
    }//GEN-LAST:event_supprimerBtnActionPerformed

    private void modifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel Df= (DefaultTableModel)Table.getModel();
        int selectedIndex = Table.getSelectedRow();
        
        try{
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            String name = nomField.getText();
            String prenom = prenomField.getText();
            int idMat = Integer.parseInt(matiereField.getText()); 
            Connect c = new Connect();
            con2 = c.getConnection();
            insert = con2.prepareStatement("update enseignant set nom=? ,prenom=?,idMat= ? where id =?");
            insert.setString(1, name);
            insert.setString(2, prenom);
            insert.setInt(3, idMat);
            insert.setInt(4, id);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Enseignant modifiée");
        nomField.setText("");
        prenomField.setText("");
        matiereField.setText("");
        nomField.requestFocus();
        table();
        
    }catch(Exception e){
        System.err.println(e);
    }
        
    }//GEN-LAST:event_modifierBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
           dispose();
            Home h = new Home();
            h.show();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel Df= (DefaultTableModel)Table.getModel();
            int selectedIndex = Table.getSelectedRow();
            nomField.setText(Df.getValueAt(selectedIndex, 1).toString());
            prenomField.setText(Df.getValueAt(selectedIndex, 2).toString());
            matiereField.setText(Df.getValueAt(selectedIndex, 3).toString());
    }//GEN-LAST:event_TableMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enseignant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton ajouterBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField matiereField;
    private javax.swing.JButton modifierBtn;
    private javax.swing.JTextField nomField;
    private javax.swing.JTextField prenomField;
    private javax.swing.JButton supprimerBtn;
    // End of variables declaration//GEN-END:variables
}
