
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ABOURA
 */
public class Filiéres extends javax.swing.JFrame {

    /**
     * Creates new form Filiéres
     */
    public Filiéres() {
        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     Connection con2;
    PreparedStatement insert;
    private void table(){
        int c;
        try{
            Connect c1 = new Connect();
            con2 = c1.getConnection();
            insert = con2.prepareStatement("select * from filiere");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            c = rss.getColumnCount();
            DefaultTableModel Df= (DefaultTableModel)Table.getModel();
            Df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int a=1;a<=c;a++){
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("nom"));
                }
                Df.addRow(v2);
            }
           
            
        }catch(Exception e) {
            System.err.println(e);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ajouterBtn = new javax.swing.JButton();
        modifierBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        supprimerBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        nomField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        ajouterBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        ajouterBtn.setForeground(new java.awt.Color(0, 153, 204));
        ajouterBtn.setText("Ajouter");
        ajouterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ajouterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 50));

        modifierBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        modifierBtn.setForeground(new java.awt.Color(0, 153, 204));
        modifierBtn.setText("Modifier ");
        modifierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierBtnActionPerformed(evt);
            }
        });
        getContentPane().add(modifierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 130, 50));

        homeBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(0, 153, 204));
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 50));

        supprimerBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        supprimerBtn.setForeground(new java.awt.Color(0, 153, 204));
        supprimerBtn.setText("Supprimer");
        supprimerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(supprimerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 150, 50));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "nom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 290, 270));

        nomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df= (DefaultTableModel)Table.getModel();
        int selectedIndex = Table.getSelectedRow();
        
        try{
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            String name = nomField.getText();
            Connect c = new Connect();
            con2 = c.getConnection();
            insert = con2.prepareStatement("update matiere set nom=? where id =?");
            insert.setString(1, name);
            insert.setInt(2, id);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Filiére modifiée");
        nomField.setText("");
        nomField.requestFocus();
        table();
        
    }catch(Exception e){
        System.err.println(e);
    }
    }//GEN-LAST:event_modifierBtnActionPerformed

    private void nomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFieldActionPerformed

    private void ajouterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBtnActionPerformed
        // TODO add your handling code here:
         String name = nomField.getText();
        try{
        Connect c = new Connect();
        con2 = c.getConnection();
        insert = con2.prepareStatement("insert into filiere(nom)values(?)");
        insert.setString(1, name);
        insert.executeUpdate();
        JOptionPane.showMessageDialog(this, "Filiére ajoutée");
        nomField.setText("");
        nomField.requestFocus();
        table();
        
    }catch(Exception e){
        System.err.println(e);
    }
        
    }//GEN-LAST:event_ajouterBtnActionPerformed

    private void supprimerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerBtnActionPerformed
        // TODO add your handling code here:
           DefaultTableModel Df= (DefaultTableModel)Table.getModel();
        int selectedIndex = Table.getSelectedRow();
        
        try{
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            int dialogResult = JOptionPane.showConfirmDialog(null,"voulez vous supprimer cette filiere","warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                Connect c = new Connect();
                con2 = c.getConnection();
                insert = con2.prepareStatement("delete from filiere where id =?");
                insert.setInt(1, id);
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this, "Filiere suprimée");
                nomField.setText("");
                nomField.requestFocus();
                table();
            }
            
            
            
        
    }catch(Exception e){
        System.err.println(e);
    }
    }//GEN-LAST:event_supprimerBtnActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df= (DefaultTableModel)Table.getModel();
            int selectedIndex = Table.getSelectedRow();
            nomField.setText(Df.getValueAt(selectedIndex, 1).toString());
    }//GEN-LAST:event_TableMouseClicked

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        Home h = new Home();
        h.show();
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filiéres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filiéres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filiéres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filiéres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filiéres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton ajouterBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifierBtn;
    private javax.swing.JTextField nomField;
    private javax.swing.JButton supprimerBtn;
    // End of variables declaration//GEN-END:variables
}
