/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 21654
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEtudiant = new javax.swing.JButton();
        btnEnseignant = new javax.swing.JButton();
        btnMatiere = new javax.swing.JButton();
        btnFiliere = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Bienvenue chez l'ISI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/female (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 40, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/courses (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 40, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/etudiant-diplome (2).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/math (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 40, 40));

        btnEtudiant.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnEtudiant.setForeground(new java.awt.Color(0, 153, 204));
        btnEtudiant.setText("Etudiant");
        btnEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtudiantActionPerformed(evt);
            }
        });
        getContentPane().add(btnEtudiant, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 112, 40));

        btnEnseignant.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnEnseignant.setForeground(new java.awt.Color(0, 153, 204));
        btnEnseignant.setText("Enseignant ");
        btnEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnseignantActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnseignant, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 115, 40));

        btnMatiere.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnMatiere.setForeground(new java.awt.Color(0, 153, 204));
        btnMatiere.setText("Matiéres");
        btnMatiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatiereActionPerformed(evt);
            }
        });
        getContentPane().add(btnMatiere, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 112, 40));

        btnFiliere.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnFiliere.setForeground(new java.awt.Color(0, 153, 204));
        btnFiliere.setText("Filéres");
        btnFiliere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiliereActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiliere, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 115, 39));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 204));
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 110, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngtree-literary-fresh-elegant-the-university-image_15358.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 620, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtudiantActionPerformed
        // TODO add your handling code here:
        Etudiant e= new Etudiant();
        dispose();
        e.show();
    }//GEN-LAST:event_btnEtudiantActionPerformed

    private void btnEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnseignantActionPerformed
        // TODO add your handling code here:
        Enseignant en = new Enseignant();
        dispose();
        en.show();
    }//GEN-LAST:event_btnEnseignantActionPerformed

    private void btnMatiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatiereActionPerformed
        // TODO add your handling code here:
        Matiéres  m = new Matiéres();
        dispose();
        m.show();
    }//GEN-LAST:event_btnMatiereActionPerformed

    private void btnFiliereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiliereActionPerformed
        // TODO add your handling code here:
        Filiéres f = new Filiéres();
        dispose();
        f.show();
    }//GEN-LAST:event_btnFiliereActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        Login l = new Login();
        l.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnseignant;
    private javax.swing.JButton btnEtudiant;
    private javax.swing.JButton btnFiliere;
    private javax.swing.JButton btnMatiere;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
